[project]
name = "oblig2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dureppoK", email = "nkk@kveim.org" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "jupyter-collaboration>=5.0.3",
]

[project.scripts]
oblig2 = "oblig2:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
